const express = require('express');
const router = express.Router();
const eventbotController = require('../controllers/eventbotController');
router.post('/registerUser', eventbotController.addRegisteredUser);
router.post('/getRegisteredUserList', eventbotController.getRegisteredUserList);
router.post('/checkinUser', eventbotController.checkinUser);
router.post('/chat/save', eventbotController.saveChat);
router.post('/chat/list', eventbotController.getChatList);
router.post('/validateRegisteredEmailId', eventbotController.validateRegisteredUserEmailId);
router.post('/getRegisteredUserCount', eventbotController.getRegisteredUserCount);
router.post('/getCheckedInUserCount', eventbotController.getCheckedInUserCount);
module.exports = router;